version: "3.9"
services:
  asterisk:
    image: andrius/asterisk:latest
    container_name: asterisk-webrtc
    restart: always
    ports:
      - "5060:5060/udp"   # Porta SIP UDP
      - "5061:5061/tcp"   # Porta SIP TLS
      - "8089:8089/tcp"   # Porta WebRTC WebSockets
      - "10000-10100:10000-10100/udp"  # Faixa RTP para chamadas
    networks:
      - asterisk_net
    volumes:
      - ./configs:/etc/asterisk
    environment:
      - TZ=America/Sao_Paulo

networks:
  asterisk_net:
    driver: bridge
